version: '3.8'

services:
  db:
    container_name: quran-bot-postgres-db
    image: postgres:18
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${PG_HOST_PORT}:${PG_CONTAINER_PORT}"
  app:
    container_name: quran-bot
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: