version: '3.8'

services:
  db:
    container_name: quran-bot-postgres-db
    image: postgres:18
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${PG_HOST_PORT}:${PG_CONTAINER_PORT}"
  redis:
    container_name: redis-cache
    image: redis:8-alpine
    ports:
     - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"
    command: redis-server --save ${REDIS_SAVE_EVERY_X_SECONDS} ${REDIS_SAVE_IF_ATLEAST_X_CHANGES_WERE_MADE} --loglevel warning --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - cache:/data
  app:
    container_name: quran-bot
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy

volumes:
  cache:
      driver: local
  postgres_data: